### PR TITLE
Solr export interface + Clean up of the entire repository

### PR DESCRIPTION
**Pull request by liseli**
This repository contains prototypes to run queries in Solr. 

**The purpose of this PR** 

* clean up the repository
* Create an API to export Solr documents given a phrase query.

**Next steps**
The logic to search and make queries can be simplified. This repository could be use in the future as back end of HT search module. 

**This huge pull request includes**:

* Revision and improvement of all the features implemented on this repository.
* Removing all the non-used code
* Documenting all the use cases in the Readme file
* Improving all the tests.
* Improving the dockerization of the application
* Creating an API to obtain the export results
* Adding the service _full_text_search_api_ to the docker-compose to run the API
I encourage you to read the README.md file, I have written it using the [template](https://github.com/hathitrust/documentation-templates) we discussed during the retreat. Feedback is welcome!

**How do we test this PR?**

```
./init.sh 
docker compose up -d
```

**Check if the API is running** Access to the URL: http://localhost:8000/docs

**Run the tests**
`docker compose exec full_text_searcher python -m pytest`

You will see the following output if all the tests ran without issue

image

[Optional] In case you want to run any of the implemented features

**Run the use case 1: Query the Solr index given a phrase**

```
docker compose exec full_text_searcher python ht_full_text_search/ht_full_text_searcher.py \          
--env dev \               
--query_string "justice blame" \                
--operator None \                                     
--query_config ocronly
```

Output: In your terminal, you should see the list of documents obtained with the input query.

image

**Run the Use case 2**: Query Solr given a list of phases (included in list_query_file.txt) and generate an CSV file with the query results.

```
docker compose exec full_text_searcher python scripts/generate_query_results_in_batch.py \  
              --env dev \
              --list_phrase_file scripts/list_query_file.txt \
              --query_config ocronly
```

Inside the folder scripts/query_results some CSV files should be generated for each of the queries included in list_query_file.txt

image

** Run the Use Case 4**: Query solr using the API

**query endpoint**: `curl --location 'http://localhost:8000/query/?query=poetic%20justice&env=dev' \
--form 'query="'\''\"poetic justice\"'\''"'`

Output: 
image

**status endpoint**: `curl --location 'http://localhost:8000/ping/'`
image

### CODE REVIEW

**Comment by moseshll** [comment]
I had the following issues with the PR, in order from trivial to error:
- My Docker complains about the Dockerfile lines 2 and 46, both `FROM` lines
  - "WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2) "
  - So basically `FROM` and `AS` should be the same upper|lower case (see https://docs.docker.com/reference/build-checks/from-as-casing/)
- I had a warning (maybe a clue to the error??) as the first line of output from `docker compose up -d`:
  - `WARN[0000] The "ENV" variable is not set. Defaulting to a blank string.`
- The service `full_text_search_api` on port 8000 crashes on launch:
```
2024-07-30 15:21:12 INFO:     Started server process [1]
2024-07-30 15:21:12 INFO:     Waiting for application startup.
2024-07-30 15:21:12 Connecting with Solr server
2024-07-30 15:21:12 ERROR:    Traceback (most recent call last):
2024-07-30 15:21:12   File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
2024-07-30 15:21:12     async with self.lifespan_context(app) as maybe_state:
2024-07-30 15:21:12   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
2024-07-30 15:21:12     return await anext(self.gen)
2024-07-30 15:21:12            ^^^^^^^^^^^^^^^^^^^^^
2024-07-30 15:21:12   File "/app/main.py", line 29, in lifespan
2024-07-30 15:21:12     exporter_api['obj'] = SolrExporter(SOLR_URL[args.env], args.env)
2024-07-30 15:21:12                                        ~~~~~~~~^^^^^^^^^^
2024-07-30 15:21:12 KeyError: ''
2024-07-30 15:21:12 
2024-07-30 15:21:12 ERROR:    Application startup failed. Exiting.
```

**Comment by liseli** [comment]
> ./init.sh

@moseshll, Before executing `docker compose up`, did you execute the script `./init.sh`? The last script should set up all the environment variables.

**Comment by liseli** [comment]
> > ./init.sh
> 
> @moseshll, Before executing `docker compose up`, did you execute the script `./init.sh`? The last script should set up all the environment variables.

I have reviewed the PR and also accepted your recommendations. I could reproduce the Warning you mentioned running `docker compose up -d` when I do docker-compose without setting the environment variables (./init.sh script). The script **init.sh** must be run before starting the container.

**Comment by moseshll** [comment]
> > @moseshll, Before executing `docker compose up`, did you execute the script `./init.sh`? The last script should set up all the environment variables.

Turns out the problem was the `.env` file left over from previous attempts. I deleted it and re-ran `./init.sh` so no errors after that when I ran `docker compose up`.

**Comment by moseshll** [comment]
All tests passed, although I had to `mkdir` the output directory `scripts/query_results` before that one (use case 2) would pass.

**Review by moseshll — APPROVED** [review]
See other comments. I would like to see `scripts/query_results` created either by the script or as part of the repository if it is needed for running standard tests, or if it is the default output location.

**Comment by liseli** [comment]
> See other comments. I would like to see `scripts/query_results` created either by the script or as part of the repository if it is needed for running standard tests, or if it is the default output location.

That makes sense, I will add this change!

**Comment by liseli** [comment]
> > See other comments. I would like to see `scripts/query_results` created either by the script or as part of the repository if it is needed for running standard tests, or if it is the default output location.
> 
> That makes sense, I will add this change!

I have applied Moses's recommendations.

**Pull request merged**
